#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="${ROOT_DIR}/.env.release.local"
FORCE=0

usage() {
  cat <<USAGE
Usage: $0 [--force] [output-path]

Creates a private macOS public-release environment file from detected local
signing state and safe placeholders.

The output file is ignored by git. Review and replace placeholders before
running scripts/release_macos_app.sh.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      OUTPUT_PATH="$1"
      ;;
  esac
  shift
done

if [[ -e "${OUTPUT_PATH}" && "${FORCE}" != "1" ]]; then
  echo "Refusing to overwrite existing release env file: ${OUTPUT_PATH}" >&2
  echo "Pass --force to replace it." >&2
  exit 2
fi

quote_shell() {
  local value="$1"
  printf "'%s'" "${value//\'/\'\\\'\'}"
}

detect_developer_id_identity() {
  security find-identity -v -p codesigning 2>/dev/null |
    sed -n 's/.*"\(Developer ID Application:[^"]*\)".*/\1/p' |
    head -n 1
}

identity="$(detect_developer_id_identity || true)"
publisher_name="Your Company, Inc."
team_id="TEAMID1234"
if [[ -n "${identity}" ]]; then
  publisher_name="$(printf '%s\n' "${identity}" | sed -E 's/^Developer ID Application: (.*) \([A-Z0-9]+\)$/\1/')"
  parsed_team_id="$(printf '%s\n' "${identity}" | sed -nE 's/^Developer ID Application: .* \(([A-Z0-9]+)\)$/\1/p')"
  if [[ -n "${parsed_team_id}" ]]; then
    team_id="${parsed_team_id}"
  fi
fi

year="$(/bin/date +%Y)"
identity_value="${identity:-Developer ID Application: Your Company, Inc. (TEAMID1234)}"

mkdir -p "$(dirname "${OUTPUT_PATH}")"
{
  cat <<HEADER
# Private AI Monitor macOS public-release environment.
# Generated by scripts/init_macos_release_env.sh.
#
# Replace every placeholder before running:
#   set -a
#   . ${OUTPUT_PATH}
#   set +a
#   ./scripts/release_macos_app.sh --check-only
#
# Do not commit this file.

HEADER
  printf 'export AI_MONITOR_BUNDLE_ID=%s\n' "$(quote_shell "com.yourcompany.aimonitor")"
  printf 'export AI_MONITOR_APP_VERSION=%s\n' "$(quote_shell "0.1.0")"
  printf 'export AI_MONITOR_APP_BUILD=%s\n' "$(quote_shell "1")"
  printf 'export AI_MONITOR_MACOS_MIN_VERSION=%s\n' "$(quote_shell "13.0")"
  printf 'export AI_MONITOR_MACOS_ARCHS=%s\n' "$(quote_shell "arm64 x86_64")"
  printf 'export AI_MONITOR_COPYRIGHT=%s\n' "$(quote_shell "Copyright ${year} ${publisher_name}")"
  printf 'export AI_MONITOR_BROWSER_EXTENSION_INSTALL_URL=%s\n' "$(quote_shell "https://chromewebstore.google.com/detail/your-ai-monitor-extension-id")"
  printf 'export AI_MONITOR_BROWSER_EXTENSION_PRIVACY_POLICY_URL=%s\n' "$(quote_shell "https://yourcompany.example/privacy/ai-monitor-browser-adapter")"
  printf 'export AI_MONITOR_CODESIGN_IDENTITY=%s\n' "$(quote_shell "${identity_value}")"
  printf 'export AI_MONITOR_NOTARY_PROFILE=%s\n' "$(quote_shell "ai-monitor-notary")"
  cat <<FOOTER

# Apple ID notary fallback for CI. Prefer AI_MONITOR_NOTARY_PROFILE locally.
# export AI_MONITOR_NOTARY_APPLE_ID='you@example.com'
# export AI_MONITOR_NOTARY_PASSWORD='app-specific-password'
# export AI_MONITOR_NOTARY_TEAM_ID='${team_id}'

export AI_MONITOR_RELEASE=1
export AI_MONITOR_CHECK_NOTARY_ONLINE=1
FOOTER
} > "${OUTPUT_PATH}"

chmod 600 "${OUTPUT_PATH}"

echo "Wrote private release env file: ${OUTPUT_PATH}"
if [[ -n "${identity}" ]]; then
  echo "Detected Developer ID identity: ${identity}"
else
  echo "No Developer ID Application identity was detected; replace the placeholder after installing the certificate."
fi
echo "Review bundle id, copyright, browser extension URLs, and notary profile before release."
